language: python

notifications:
  email:
    - shihyuay@uci.edu
    - qingronz@uci.edu

os:
  - linux

python:
  - "3.6"

env:
  - COVERAGE_RCFILE=".coveragerc" PYLINTRC=".pylintrc"

install:
  - pip install -r requirements_dev.txt
  - pip install -r requirements.txt

script:
  - cd ./tests
  - pytest --disable-pytest-warnings test.py