language: python

notifications:
  email:
    - shihyuay@uci.edu
<<<<<<< HEAD
=======
    - qingronz@uci.edu
>>>>>>> master

os:
  - linux

python:
  - "3.6"

env:
  - COVERAGE_RCFILE=".coveragerc" PYLINTRC=".pylintrc"

install:
<<<<<<< HEAD
=======
  - pip install .
  - pip install -r requirements_dev.txt
>>>>>>> master
  - sudo add-apt-repository universe
  - sudo apt update
  - sudo apt install graphviz
  - pip install pygraphviz
<<<<<<< HEAD
  - pip install -r requirements_dev.txt
  - pip install -r requirements.txt
=======
>>>>>>> master
  - pip install torch==1.6.0+cpu torchvision==0.7.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
  - pip install --no-index torch-scatter -f https://pytorch-geometric.com/whl/torch-1.6.0+cpu.html
  - pip install --no-index torch-sparse -f https://pytorch-geometric.com/whl/torch-1.6.0+cpu.html
  - pip install --no-index torch-cluster -f https://pytorch-geometric.com/whl/torch-1.6.0+cpu.html
  - pip install --no-index torch-spline-conv -f https://pytorch-geometric.com/whl/torch-1.6.0+cpu.html
<<<<<<< HEAD
  - pip install torch-geometric
  - pip install pyverilog
  - pip install pyunpack
  - pip install patool


script:
  - cd ./tests
  - pytest --disable-pytest-warnings test.py
=======
  - pip install torch-geometric==1.6.1

script:
  - cd ./tests
  - pytest --disable-pytest-warnings test.py
>>>>>>> master
