language: python

notifications:
  email:
    - shihyuay@uci.edu
    - qingronz@uci.edu

os:
  - linux

python:
  - "3.6"

env:
  - COVERAGE_RCFILE=".coveragerc" PYLINTRC=".pylintrc"

install:
  - pip install torch==1.6.0+cpu torchvision==0.7.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
  - pip install --no-index torch-scatter -f https://pytorch-geometric.com/whl/torch-1.6.0+cpu.html
  - pip install --no-index torch-sparse -f https://pytorch-geometric.com/whl/torch-1.6.0+cpu.html
  - pip install --no-index torch-cluster -f https://pytorch-geometric.com/whl/torch-1.6.0+cpu.html
  - pip install --no-index torch-spline-conv -f https://pytorch-geometric.com/whl/torch-1.6.0+cpu.html
  - pip install torch-geometric
  - pip install -r requirements_dev.txt
  - pip install -r requirements.txt

script:
  - cd ./tests
  - pytest --disable-pytest-warnings test.py