---
learning_rate: 0.001 # The initial learning rate for the model.
seed: 0 # Random seed.
epochs: 200 # Number of epochs to train.
weight_decay: 5e-4 # Weight decay (L2 loss on parameters).
hidden: 200 # Number of hidden units.
dropout: 0.5 # Dropout rate (1 - keep probability).
batch_size: 4 # Number of graphs in a batch.
model: "gcn" # Model to be used.
num_layer: 5 # Number of layers in the neural network.
hidden_dim: 32 # Hidden dimension in GIN.
test_step: 10 # The interval between mini evaluation along the training process.
pooling_type: "sagpool" # Graph pooling type.
readout_type: "max" # Readout type.
ratio: 0.8 # Dataset splitting ratio
poolratio: 0.75 # Ratio for graph pooling.
raw_dataset_path: "/home/louisccc/NAS/louisccc/hw2vec/datasets/TJ-RTL/" # Path to raw dataset for parsing if no precache.
embed_dim: 2 # The dimension of graph embeddings.
data_pkl_path: "./DFG-TJ-RTL.pkl" # Path to the pickle file storing the graph dataset
graph_type: "DFG" # Graph type to create.
NORMALIZATION: "type_only" # or "keep_variable"
model_path: "./best_result" # Path to store best performing model weights.